const unit1 = [
    "Conjunct Motion",
    "Disjunct Motion",
    "Scale",
    "Major Scale",
    "Natural Minor Scale",
    "Harmonic Minor Scale",
    "Melodic Minor Scale",
    "Pentatonic Scale",
    "Chromatic Scale",
    "Whole Tone Scale",
    "Relative Minor",
    "Parallel Minor",
    "Accidental",
    "Sharp",
    "Flat",
    "Double Sharp",
    "Double Flat",
    "Natural",
    "Enharmonic",
    "Staff",
    "Treble Clef",
    "Bass Clef",
    "Ledger Lines",
    "Key",
    "Key Signature",
    "Solfege",
    "Slur",
    "Tie",
    "Rhythm",
    "Measure",
    "Time Signature",
    "Meter",
    "Simple Meter",
    "Compound Meter",
    "Complex Meter",
    "Tonic",
    "Supertonic",
    "Mediant",
    "Subdominant",
    "Dominant",
    "Submediant",
    "Leading Tone",
    "Tempo",
    "BPM",
    "Ritardando",
    "Accelerando",
    "A Tempo",
    "Rubato",
    "Largo/Lento",
    "Adagio",
    "Andante",
    "Moderato",
    "Allegro",
    "Vivace",
    "Presto",
    "Syncopation",
    "Downbeat",
    "Upbeat",
    "Duple Pulse",
    "Triple Pulse",
    "Quadruple Pulse",
];

const unit2 = [
    "Perfect Unison",
    "Minor 2",
    "Major 2",
    "Minor 3",
    "Major 3",
    "Perfect 4",
    "Tritone",
    "Perfect 5",
    "Minor 6",
    "Major 6",
    "Minor 7",
    "Major 7",
    "Perfect Octave",
    "Function",
    "Motive",
    "Anacrusis",
    "Contour",
    "Alberti Bass",
    "Countermelody",
    "Harmony",
    "Arpeggio",
    "Accompaniment",
    "Orchestration",
    "Phrase",
    "Maestoso",
    "Glissando",
    "Octatonic Scale",
    "Ascend",
    "Descend",
    "Improvisation",
    "Dissonance",
    "Consonance",
    "Texture",
    "Monophonic",
    "Homophonic",
    "Polyphonic",
    "Heterophonic",
    "Solo",
    "Duet",
    "Trio",
    "Quartet",
    "Soprano",
    "Alto",
    "Tenor",
    "Bass",
    "Transpose",
    "Dictation",
    "Diatonic",
    "Non-Diatonic",
    "Melismatic",
    "Syllabic",
    "Cross Rhythm",
    "Hemiola",
    "Compound Interval",
    "Ostinato",
    "Canon",
    "Sequence",
    "Tonal Sequence",
    "Real Sequence",
    "Melodic Inversion",
    "Melodic Retrograde",
    "Fragmentation",
    "Theme",
    "Imitation",
    "Rhythmic Diminution",
    "Rhythmic Augmentation",
    "Leitmotif",
    "Walking Bass",
    "Agogic Accent",
    "Doubling",
    "Counterpoint",
    "Basso Continuo",
    "Rhythm Section",
];

const unit3 = [
    
]

const unit4 = [
    
]

const unit5 = [
    
];




const cumulative = [
    "Conjunct Motion",
    "Disjunct Motion",
    "Scale",
    "Major Scale",
    "Natural Minor Scale",
    "Harmonic Minor Scale",
    "Melodic Minor Scale",
    "Pentatonic Scale",
    "Chromatic Scale",
    "Whole Tone Scale",
    "Relative Minor",
    "Parallel Minor",
    "Accidental",
    "Sharp",
    "Flat",
    "Double Sharp",
    "Double Flat",
    "Natural",
    "Enharmonic",
    "Staff",
    "Treble Clef",
    "Bass Clef",
    "Ledger Lines",
    "Key",
    "Key Signature",
    "Solfege",
    "Slur",
    "Tie",
    "Rhythm",
    "Measure",
    "Time Signature",
    "Meter",
    "Simple Meter",
    "Compound Meter",
    "Complex Meter",
    "Tonic",
    "Supertonic",
    "Mediant",
    "Subdominant",
    "Dominant",
    "Submediant",
    "Leading Tone",
    "Tempo",
    "BPM",
    "Ritardando",
    "Accelerando",
    "A Tempo",
    "Rubato",
    "Largo/Lento",
    "Adagio",
    "Andante",
    "Moderato",
    "Allegro",
    "Vivace",
    "Presto",
    "Syncopation",
    "Downbeat",
    "Upbeat",
    "Duple Pulse",
    "Triple Pulse",
    "Quadruple Pulse",
    "Perfect Unison",
    "Minor 2",
    "Major 2",
    "Minor 3",
    "Major 3",
    "Perfect 4",
    "Tritone",
    "Perfect 5",
    "Minor 6",
    "Major 6",
    "Minor 7",
    "Major 7",
    "Perfect Octave",
    "Function",
    "Motive",
    "Anacrusis",
    "Contour",
    "Alberti Bass",
    "Countermelody",
    "Harmony",
    "Arpeggio",
    "Accompaniment",
    "Orchestration",
    "Phrase",
    "Maestoso",
    "Glissando",
    "Octatonic Scale",
    "Ascend",
    "Descend",
    "Improvisation",
    "Dissonance",
    "Consonance",
    "Texture",
    "Monophonic",
    "Homophonic",
    "Polyphonic",
    "Heterophonic",
    "Solo",
    "Duet",
    "Trio",
    "Quartet",
    "Soprano",
    "Alto",
    "Tenor",
    "Bass",
    "Transpose",
    "Dictation",
    "Diatonic",
    "Non-Diatonic",
    "Melismatic",
    "Syllabic",
    "Cross Rhythm",
    "Hemiola",
    "Compound Interval",
    "Ostinato",
    "Canon",
    "Sequence",
    "Tonal Sequence",
    "Real Sequence",
    "Melodic Inversion",
    "Melodic Retrograde",
    "Fragmentation",
    "Theme",
    "Imitation",
    "Rhythmic Diminution",
    "Rhythmic Augmentation",
    "Leitmotif",
    "Walking Bass",
    "Agogic Accent",
    "Doubling",
    "Counterpoint",
    "Basso Continuo",
    "Rhythm Section",
    ];

    const theglossary = [
        {"Term":"Conjunct Motion","Definition":"Smooth voice leading, usually by step"}, 
        {"Term":"Disjunct Motion","Definition":"Voice leading characterized by large leaps"}, 
        {"Term":"Scale","Definition":"The notes of a given key, ascending and descending"}, 
        {"Term":"Major Scale","Definition":"1, 2, 3, 4, 5, 6, 7, 8"}, 
        {"Term":"Natural Minor Scale","Definition":"1, 2,♭3, 4, 5,♭6,♭7, 8"}, 
        {"Term":"Harmonic Minor Scale","Definition":"1, 2,♭3, 4, 5,♭6,♮7, 8"}, 
        {"Term":"Melodic Minor Scale","Definition":"1, 2,♭3, 4, 5,♮6,♮7, 8 ↗︎ ♭7,♭6, 5, 4,♭3, 2, 1 ↘︎"}, 
        {"Term":"Pentatonic Scale","Definition":"A scale only using 5 notes, major or minor"}, 
        {"Term":"Chromatic Scale","Definition":"A scale utilizing all 12 notes"}, 
        {"Term":"Whole Tone Scale","Definition":"A scale comprised only of whole steps"}, 
        {"Term":"Relative Minor","Definition":"A minor scale that uses the same key signature as the major (C major, A minor)"}, 
        {"Term":"Parallel Minor","Definition":"A minor scale that shares the same tonic as the major (C major, C minor)"}, 
        {"Term":"Accidental","Definition":"Markings in the music that alter the pitch of a note"}, 
        {"Term":"Sharp","Definition":"Raises a natural pitch by one half step"}, 
        {"Term":"Flat","Definition":"Lowers a natural pitch by one half step"}, 
        {"Term":"Double Sharp","Definition":"Raises a natural pitch by two half steps"}, 
        {"Term":"Double Flat","Definition":"Lowers a natural pitch by two half steps"}, 
        {"Term":"Natural","Definition":"Returns a note to it’s natural state, canceling any accidentals"}, 
        {"Term":"Enharmonic","Definition":"An alternate spelling of a note (i.e. C#/Db)"}, 
        {"Term":"Staff","Definition":"The five lines you write music on"}, 
        {"Term":"Treble Clef","Definition":"G clef, the symbol representing the upper register"}, 
        {"Term":"Bass Clef","Definition":"F clef, the symbol representing the lower register"}, 
        {"Term":"Ledger Lines","Definition":"Short lines written above and below the staff"}, 
        {"Term":"Key","Definition":"The scale used in a piece of music"}, 
        {"Term":"Key Signature","Definition":"The set of sharps and flats which determine the key"}, 
        {"Term":"Solfege","Definition":"Do, Re, Mi, etc."}, 
        {"Term":"Slur","Definition":"A curved line between two different pitches, indicating that they should be played legato"}, 
        {"Term":"Tie","Definition":"A curved line between two notes of the same pitch, adding their lengths together"}, 
        {"Term":"Rhythm","Definition":"The way of organizing notes by length"}, 
        {"Term":"Measure","Definition":"The space between two vertical bar lines"}, 
        {"Term":"Time Signature","Definition":"A marking that describes the number of beats in a measure and how they are subdivided"}, 
        {"Term":"Meter","Definition":"Another way to say Time Signature"}, 
        {"Term":"Simple Meter","Definition":"Beat is divisible by groups of two"}, 
        {"Term":"Compound Meter","Definition":"Beat is divisible by groups of three"}, 
        {"Term":"Complex Meter","Definition":"Some beats are divisible by two, some by three (asymmetric)"},
        {"Term":"Tonic","Definition":"Scale Degree I, do-mi-sol"}, 
        {"Term":"Supertonic","Definition":"Scale Degree ii, re-fa-la"}, 
        {"Term":"Mediant","Definition":"Scale Degree iii, mi-sol-xi"}, 
        {"Term":"Subdominant","Definition":"Scale Degree IV, fa-la-do"}, 
        {"Term":"Dominant","Definition":"Scale Degree V, sol-xi-re"}, 
        {"Term":"Submediant","Definition":"Scale Degree vi, la-do-mi"}, 
        {"Term":"Leading Tone","Definition":"Scale Degree viiº, xi-re-fa"}, 
        {"Term":"Tempo","Definition":"The speed of music"}, 
        {"Term":"BPM","Definition":"The number of beats per minute"}, 
        {"Term":"Ritardando","Definition":"To gradually decrease in speed"}, 
        {"Term":"Accelerando","Definition":"To gradually increase in speed"}, 
        {"Term":"A Tempo","Definition":"To return to the original tempo (after rit/accel)"}, 
        {"Term":"Rubato","Definition":"To be played with free tempo"}, 
        {"Term":"Largo/Lento","Definition":"Very slow, 40-60 BPM"}, 
        {"Term":"Adagio","Definition":"Slowly, with expression, 60-75 BPM"}, 
        {"Term":"Andante","Definition":"Walking tempo, 75-90 BPM"}, 
        {"Term":"Moderato","Definition":"At a moderate speed, 100-120 BPM"}, 
        {"Term":"Allegro","Definition":"Fast, 120-140 BPM"}, 
        {"Term":"Vivace","Definition":"Lively and fast, 150-175 BPM"}, 
        {"Term":"Presto","Definition":"Very fast, 140-200 BPM"}, 
        {"Term":"Syncopation","Definition":"Music/rhythms that accent the upbeats of a phrase"}, 
        {"Term":"Downbeat","Definition":"The beginning/strongest part of the beat"}, 
        {"Term":"Upbeat","Definition":"The weaker subdivision(s) between the beats"}, 
        {"Term":"Duple Pulse","Definition":"Time signature with two main beats"}, 
        {"Term":"Triple Pulse","Definition":"Time signature with three main beats"}, 
        {"Term":"Quadruple Pulse","Definition":"Time signature with four main beats"},
        {"Term":"Perfect Unison","Definition":"No distance between the pitches; the same note"}, 
        {"Term":"Minor 2","Definition":"One half step between the pitches, “Jaws”"}, 
        {"Term":"Major 2","Definition":"Two half steps between the pitches, “Do-re”"}, 
        {"Term":"Minor 3","Definition":"Three half steps between the pitches, “Funeral March”"}, 
        {"Term":"Major 3","Definition":"Four half steps between the pitches, “Mario”"}, 
        {"Term":"Perfect 4","Definition":"Five half steps between the pitches, “Here comes the bride,” “起来”"}, 
        {"Term":"Tritone","Definition":"Six half steps between the pitches, “The Simpsons”"}, 
        {"Term":"Perfect 5","Definition":"Seven half steps between the pitches, “Star Wars”"}, 
        {"Term":"Minor 6","Definition":"Eight half steps between the pitches, “Romance,” “Bad Romance”"}, 
        {"Term":"Major 6","Definition":"Nine half steps between the pitches, “NBC,” “Not At All”"}, 
        {"Term":"Minor 7","Definition":"Ten half steps between the pitches, “Winnie the Pooh”"}, 
        {"Term":"Major 7","Definition":"Eleven half steps between the pitches, “Pure Imagination”"}, 
        {"Term":"Perfect Octave","Definition":"Twelve half steps between the pitches, space of 8 notes"}, 
        {"Term":"Timbre","Definition":"The quality or tone color of a sound"}, 
        {"Term":"Function","Definition":"The specific role (job) that a chord plays "}, 
        {"Term":"Motive","Definition":"A musical idea, piece of melody that is important to the song as a whole"}, 
        {"Term":"Anacrusis","Definition":"A pickup note that starts before the beginning of a phrase"}, 
        {"Term":"Contour","Definition":"The shape of a given melody or phrase"}, 
        {"Term":"Alberti Bass","Definition":"The practice of arpeggiating the chords under the main melody"}, 
        {"Term":"Countermelody","Definition":"A secondary melody that accompanies the main one"}, 
        {"Term":"Harmony","Definition":"The general concept that describes the way notes sound together"}, 
        {"Term":"Arpeggio","Definition":"Playing a chord one note at a time instead of all at once"}, 
        {"Term":"Accompaniment","Definition":"A musical part of lesser importance, mostly serving to give the harmony"}, 
        {"Term":"Orchestration","Definition":"The selection of instruments that play a particular part (instrumentation)"}, 
        {"Term":"Phrase","Definition":"A short segment of music with a clearly defined beginning and end"}, 
        {"Term":"Maestoso","Definition":"To be played majestically, by accenting every note (bouncy)"}, 
        {"Term":"Glissando","Definition":"To quickly slide from a low note to a high note, or vice versa"}, 
        {"Term":"Octatonic Scale","Definition":"A scale using 8 notes, diminished scales"}, 
        {"Term":"Ascend","Definition":"To go up"}, 
        {"Term":"Descend","Definition":"To go down"}, 
        {"Term":"Improvisation","Definition":"Come up with new melodies, solos, etc. on the spot"}, 
        {"Term":"Dissonance","Definition":"A sound of clashing produced by conflicting notes"}, 
        {"Term":"Consonance","Definition":"The opposite of dissonance, pleasant sounds"}, 
        {"Term":"Texture","Definition":"The way in which musical content is presented"}, 
        {"Term":"Monophonic","Definition":"A musical texture consisting of a single melody, if multiple voices, sung in unison"}, 
        {"Term":"Homophonic","Definition":"A musical texture consisting of a main melody and harmony of lesser importance"}, 
        {"Term":"Polyphonic","Definition":"A musical texture using multiple melodies, each with semi-equal importance"}, 
        {"Term":"Heterophonic","Definition":"A musical texture of a melody that is doubled but with slight variations"}, 
        {"Term":"Solo","Definition":"A performance by a single musician"}, 
        {"Term":"Duet","Definition":"Two musicians performing together"}, 
        {"Term":"Trio","Definition":"Three musicians performing together"}, 
        {"Term":"Quartet","Definition":"Four Musicians performing together"}, 
        {"Term":"Soprano","Definition":"The upper female voice"}, 
        {"Term":"Alto","Definition":"The lower female voice"}, 
        {"Term":"Tenor","Definition":"The upper male voice"}, 
        {"Term":"Bass","Definition":"The lower male voice"}, 
        {"Term":"Transpose","Definition":"To move all the notes of a song up or down"}, 
        {"Term":"Dictation","Definition":"To write down a given melody or harmony"}, 
        {"Term":"Diatonic","Definition":"Chords or notes that fall within the scale"}, 
        {"Term":"Non-Diatonic","Definition":"Chords or notes that fall outside of the scale"}, 
        {"Term":"Melismatic","Definition":"To sing one syllable with many notes"}, 
        {"Term":"Syllabic","Definition":"To sing one note per syllable"}, 
        {"Term":"Cross Rhythm","Definition":"An overlapping of different rhythms / divisions of the beat"}, 
        {"Term":"Hemiola","Definition":"In a 3/4 section of music, a rhythmic grouping of 2. Provides rhythmic tension."}, 
        {"Term":"Compound Interval","Definition":"An interval that is larger than an octave"}, 
        {"Term":"Ostinato","Definition":"A repeated musical phrase"}, 
        {"Term":"Canon","Definition":"A polyphonic texture created by playing/singing the same melody at different times"},
        {"Term":"Sequence","Definition":"A repetition of a musical phrase at a higher or lower pitch point"}, 
        {"Term":"Tonal Sequence","Definition":"A sequence that stays in the same key, a diatonic sequence"}, 
        {"Term":"Real Sequence","Definition":"A sequence that keeps the exact intervalic relationships intact, usually outside of the key"}, 
        {"Term":"Melodic Inversion","Definition":"To flip a melody vertically, to play it upside down"}, 
        {"Term":"Melodic Retrograde","Definition":"To flip a melody horizontally, to play it backwards"}, 
        {"Term":"Fragmentation","Definition":"Taking small pieces of a melody and using it to write others"}, 
        {"Term":"Theme","Definition":"The main melodic subject of a piece"}, 
        {"Term":"Imitation","Definition":"The act of mimicking melodies in the same composition"}, 
        {"Term":"Rhythmic Diminution","Definition":"Shortening the lengths of all notes in a phrase (doubling the speed)"}, 
        {"Term":"Rhythmic Augmentation","Definition":"Lengthening the lengths of all notes in a phrase (slows the speed x2)"}, 
        {"Term":"Leitmotif","Definition":"The practice of assigning themes and melodies to specific characters"}, 
        {"Term":"Walking Bass","Definition":"A bassline that ascends and descends, scalularly"},
        {"Term":"Agogic Accent","Definition":"To lengthen or slightly delay a note to add further emphasis to it"}, 
        {"Term":"Doubling","Definition":"Playing the same notes as another instrument (can be transposed up/down by octave)"}, 
        {"Term":"Counterpoint","Definition":"The art of writing multiple melodies"}, 
        {"Term":"Basso Continuo","Definition":"The instrument(s) responsible for providing accompaniment in baroque music"}, 
        {"Term":"Rhythm Section","Definition":"The instrument(s) responsible for providing accompaniment in jazz music"},
    ];