const unit1 = [
    "Conjunct Motion",
    "Disjunct Motion",
    "Scale",
    "Major Scale",
    "Natural Minor Scale",
    "Harmonic Minor Scale",
    "Melodic Minor Scale",
    "Pentatonic Scale",
    "Chromatic Scale",
    "Whole Tone Scale",
    "Relative Minor",
    "Parallel Minor",
    "Accidental",
    "Sharp",
    "Flat",
    "Double Sharp",
    "Double Flat",
    "Natural",
    "Enharmonic",
    "Staff",
    "Treble Clef",
    "Bass Clef",
    "Ledger Lines",
    "Key",
    "Key Signature",
    "Solfege",
    "Slur",
    "Tie",
    "Rhythm",
    "Measure",
    "Time Signature",
    "Meter",
    "Simple Meter",
    "Compound Meter",
    "Complex Meter",
    "Tonic",
    "Supertonic",
    "Mediant",
    "Subdominant",
    "Dominant",
    "Submediant",
    "Leading Tone",
    "Tempo",
    "BPM",
    "Ritardano",
    "Accelerando",
    "A Tempo",
    "Rubato",
    "Largo/Lento",
    "Adagio",
    "Andante",
    "Moderato",
    "Allegro",
    "Vivace",
    "Presto",
    "Syncopation",
    "Downbeat",
    "Upbeat",
    "Duple Pulse",
    "Triple Pulse",
    "Quadruple Pulse",
];

const unit2 = [
    
];

const unit3 = [
    
]

const unit4 = [
    
]

const unit5 = [
    
];




const cumulative = [
    "Conjunct Motion",
    "Disjunct Motion",
    "Scale",
    "Major Scale",
    "Natural Minor Scale",
    "Harmonic Minor Scale",
    "Melodic Minor Scale",
    "Pentatonic Scale",
    "Chromatic Scale",
    "Whole Tone Scale",
    "Relative Minor",
    "Parallel Minor",
    "Accidental",
    "Sharp",
    "Flat",
    "Double Sharp",
    "Double Flat",
    "Natural",
    "Enharmonic",
    "Staff",
    "Treble Clef",
    "Bass Clef",
    "Ledger Lines",
    "Key",
    "Key Signature",
    "Solfege",
    "Slur",
    "Tie",
    "Rhythm",
    "Measure",
    "Time Signature",
    "Meter",
    "Simple Meter",
    "Compound Meter",
    "Complex Meter",
    "Tonic",
    "Supertonic",
    "Mediant",
    "Subdominant",
    "Dominant",
    "Submediant",
    "Leading Tone",
    "Tempo",
    "BPM",
    "Ritardano",
    "Accelerando",
    "A Tempo",
    "Rubato",
    "Largo/Lento",
    "Adagio",
    "Andante",
    "Moderato",
    "Allegro",
    "Vivace",
    "Presto",
    "Syncopation",
    "Downbeat",
    "Upbeat",
    "Duple Pulse",
    "Triple Pulse",
    "Quadruple Pulse",
    ];

    const theglossary = [
        {"Term":"Conjunct Motion","Definition":"Smooth voice leading, usually by step"}, 
        {"Term":"Disjunct Motion","Definition":"Voice leading characterized by large leaps"}, 
        {"Term":"Scale","Definition":"The notes of a given key, ascending and descending"}, 
        {"Term":"Major Scale","Definition":"1, 2, 3, 4, 5, 6, 7, 8"}, 
        {"Term":"Natural Minor Scale","Definition":"1, 2,♭3, 4, 5,♭6,♭7, 8"}, 
        {"Term":"Harmonic Minor Scale","Definition":"1, 2,♭3, 4, 5,♭6,♮7, 8"}, 
        {"Term":"Melodic Minor Scale","Definition":"1, 2,♭3, 4, 5,♮6,♮7, 8 ↗︎ ♭7,♭6, 5, 4,♭3, 2, 1 ↘︎"}, 
        {"Term":"Pentatonic Scale","Definition":"A scale only using 5 notes, major or minor"}, 
        {"Term":"Chromatic Scale","Definition":"A scale utilizing all 12 notes"}, 
        {"Term":"Whole Tone Scale","Definition":"A scale comprised only of whole steps"}, 
        {"Term":"Relative Minor","Definition":"A minor scale that uses the same key signature as the major (C major, A minor)"}, 
        {"Term":"Parallel Minor","Definition":"A minor scale that shares the same tonic as the major (C major, C minor)"}, 
        {"Term":"Accidental","Definition":"Markings in the music that alter the pitch of a note"}, 
        {"Term":"Sharp","Definition":"Raises a natural pitch by one half step"}, 
        {"Term":"Flat","Definition":"Lowers a natural pitch by one half step"}, 
        {"Term":"Double Sharp","Definition":"Raises a natural pitch by two half steps"}, 
        {"Term":"Double Flat","Definition":"Lowers a natural pitch by two half steps"}, 
        {"Term":"Natural","Definition":"Returns a note to it’s natural state, canceling any accidentals"}, 
        {"Term":"Enharmonic","Definition":"An alternate spelling of a note (i.e. C#/Db)"}, 
        {"Term":"Staff","Definition":"The five lines you write music on"}, 
        {"Term":"Treble Clef","Definition":"G clef, the symbol representing the upper register"}, 
        {"Term":"Bass Clef","Definition":"F clef, the symbol representing the lower register"}, 
        {"Term":"Ledger Lines","Definition":"Short lines written above and below the staff"}, 
        {"Term":"Key","Definition":"The scale used in a piece of music"}, 
        {"Term":"Key Signature","Definition":"The set of sharps and flats which determine the key"}, 
        {"Term":"Solfege","Definition":"Do, Re, Mi, etc."}, 
        {"Term":"Slur","Definition":"A curved line between two different pitches, indicating that they should be played legato"}, 
        {"Term":"Tie","Definition":"A curved line between two notes of the same pitch, adding their lengths together"}, 
        {"Term":"Rhythm","Definition":"The way of organizing notes by length"}, 
        {"Term":"Measure","Definition":"The space between two vertical bar lines"}, 
        {"Term":"Time Signature","Definition":"A marking that describes the number of beats in a measure and how they are subdivided"}, 
        {"Term":"Meter","Definition":"Another way to say Time Signature"}, 
        {"Term":"Simple Meter","Definition":"Beat is divisible by groups of two"}, 
        {"Term":"Compound Meter","Definition":"Beat is divisible by groups of three"}, 
        {"Term":"Complex Meter","Definition":"Some beats are divisible by two, some by three (asymmetric)"},
        {"Term":"Tonic","Definition":"Scale Degree I, do-mi-sol"}, 
        {"Term":"Supertonic","Definition":"Scale Degree ii, re-fa-la"}, 
        {"Term":"Mediant","Definition":"Scale Degree iii, mi-sol-xi"}, 
        {"Term":"Subdominant","Definition":"Scale Degree IV, fa-la-do"}, 
        {"Term":"Dominant","Definition":"Scale Degree V, sol-xi-re"}, 
        {"Term":"Submediant","Definition":"Scale Degree vi, la-do-mi"}, 
        {"Term":"Leading Tone","Definition":"Scale Degree viiº, xi-re-fa"}, 
        {"Term":"Tempo","Definition":"The speed of music"}, 
        {"Term":"BPM","Definition":"The number of beats per minute"}, 
        {"Term":"Ritardano","Definition":"To gradually decrease in speed"}, 
        {"Term":"Accelerando","Definition":"To gradually increase in speed"}, 
        {"Term":"A Tempo","Definition":"To return to the original tempo (after rit/accel)"}, 
        {"Term":"Rubato","Definition":"To be played with free tempo"}, 
        {"Term":"Largo/Lento","Definition":"Very slow, 40-60 BPM"}, 
        {"Term":"Adagio","Definition":"Slowly, with expression, 60-75 BPM"}, 
        {"Term":"Andante","Definition":"Walking tempo, 75-90 BPM"}, 
        {"Term":"Moderato","Definition":"At a moderate speed, 100-120 BPM"}, 
        {"Term":"Allegro","Definition":"Fast, 120-140 BPM"}, 
        {"Term":"Vivace","Definition":"Lively and fast, 150-175 BPM"}, 
        {"Term":"Presto","Definition":"Very fast, 140-200 BPM"}, 
        {"Term":"Syncopation","Definition":"Music/rhythms that accent the upbeats of a phrase"}, 
        {"Term":"Downbeat","Definition":"The beginning/strongest part of the beat"}, 
        {"Term":"Upbeat","Definition":"The weaker subdivision(s) between the beats"}, 
        {"Term":"Duple Pulse","Definition":"Time signature with two main beats"}, 
        {"Term":"Triple Pulse","Definition":"Time signature with three main beats"}, 
        {"Term":"Quadruple Pulse","Definition":"Time signature with four main beats"},
    ];